### ISSUE TITLE
Reflections on model

### ISSUE THREAD

**Issue by Dzi4d3k** [TeamFSIModding/FS17_Goweil_LT_Master#42]
I see that there are specular textures, but I have impression that it is not visible on machine in game. Is the mat effect intended?

**Comment by TyKonKet** [comment]
I'm not sure, but as I understood from the modeller, this is the intended effect...
PS:
Did you found the *.shapes?

**Comment by Dzi4d3k** [comment]
OK, a manage to got shapes file, but if you wish I could remove them on your request, but I think this was intended move, right? :-)

**Comment by TyKonKet** [comment]
Yes, keep them!

**Comment by Dzi4d3k** [comment]
Thank, you, I'll to more tests later today.

**Comment by TyKonKet** [comment]
> Also I'm not sure how it fit Giants's FS17 models standard and if it does matter or not.
I see that some don't like the shine effect, as there are used to FS13 models, but as far as I remember Giants wrote that model should resemblance real equipment, and real doesn't look mat
  
I agree with you but I can't do too much for this, the modeller is convinced that this is the right and best way to do textures...

**Comment by Dzi4d3k** [comment]
Ok, I'm fine with that, I wanted just to notice the remarks.
