### ISSUE TITLE
Conveyor belt and other issues

### ISSUE THREAD

**Issue by Dzi4d3k** [TeamFSIModding/FS17_Goweil_LT_Master#45]
I have following doubts:
- Conveyor belt working only when there is stuff inside the drop 
- There is text in translation file for enabling/disabling conveyor belt, but there is no such option near machine
- the drop off part is missing bottom collision:

![fsscreen_2017_05_31_23_35_43](https://cloud.githubusercontent.com/assets/12050055/26655168/f6273f9c-4659-11e7-8498-ae78201d842f.png)

**Comment by Dzi4d3k** [comment]
Next:
- when shovel is too low it tip on ground under conveyor belt

**Comment by TyKonKet** [comment]
- I didn't understand if this is a bug or what 😄 
- This is an old text that we will probably use for future purposes
- To fix
- To fix

**Comment by Dzi4d3k** [comment]
I assume that after enabling machine conveyor belt should work regardless of there is material on it or not. Now it works only if there is material on it. I mean the animation of working conveyor belt.

**Comment by Dzi4d3k** [comment]
Next:
- animation of bale sliding from wrapper is not quite good, it is lowered too low, and jump up to ground.

**Comment by TyKonKet** [comment]
> I assume that after enabling machine conveyor belt should work regardless of there is material on it or not. Now it works only if there is material on it. I mean the animation of working conveyor belt.

Maybe you're right but we prefer to keep it in this way for technical reasons

> animation of bale sliding from wrapper is not quite good, it is lowered too low, and jump up to ground.

We already fixed that, this was an error introduced by a miss copy-paste xD

**Comment by Dzi4d3k** [comment]
Ok, I got it.

Now, fill type is change immediately with automatic removal of previous one, regardless of its volume.
Is this intended? I saw translation texts about clearing machine first.

**Comment by TyKonKet** [comment]
Yes, are you talking abount material in the baling chamber or in the back?
The one in the back should never change, if you want to use a different fill type you must clear it, the baling chamber have the default behaviour, it change instantly when the fill type changes.

**Comment by Dzi4d3k** [comment]
Well, I wasn't be able to put new material before it gone to chamber and back conveyor was already empty, but then chamber fill was reset and new material was transported to it.

**Comment by TyKonKet** [comment]
Yes, i know that, but i chose this solution because all balers works in this way

**Comment by Dzi4d3k** [comment]
>Yes, i know that, but i chose this solution because all balers works in this way.
All players knows this and i don't want to make this mod more complex than it already is.

Yes, you are right, this machine is so different from other available in game that I forgot about this. I can look for other issues if you like, however it is not much time left.

**Comment by TyKonKet** [comment]
@Dzi4d3k if you want and you have time to keep testing, i'll will fix until the last minutes of the mod contest.

**Comment by Dzi4d3k** [comment]
I do not dare to ask, but would you mind sharing latest shapes, as I don't wan't to report on what is already fixed. Preferably, for mod security, privatively on slack or any other direct message. Otherwise I'll be OK to test against what I already have :-)

**Comment by TyKonKet** [comment]
How can i contact you in private?

**Comment by Dzi4d3k** [comment]
At Realismus Modding Slack? I know you have account already there.

**Comment by Dzi4d3k** [comment]
I sent you direct message there.

**Comment by WetBullet** [comment]
im  having  issues  opening  right side  door  ??????? N key  no work ? reinstalled  and same  issues  .  ladder  unfolds and  work  position  works  but to get it to  unfold completely  i can opne  side  panel

**Comment by fcelsa** [comment]
You need to mantain tractor on, set manual ignition in game settings.

**Comment by fcelsa** [comment]
some of the issue was overcome in first release and other commit, I close this.
