### ISSUE TITLE
Game won't  load when mod is active

### ISSUE THREAD

**Issue by Bede16** [TeamFSIModding/FS17_Goweil_LT_Master#48]
Hey Guys,
I was looking forward to play this mod but unfortunately it just produces an issue.

[log.txt](https://github.com/TeamFSIModding/FS17_Goweil_LT_Master/files/1064574/log.txt)

I hope you can help me solve this problem.

**Comment by fcelsa** [comment]
Yes sure, you have several options:
1) set language to english
2) edit file translations/l10n_de.xml like you can see here: https://github.com/TeamFSIModding/FS17_Goweil_LT_Master/commit/1f4153206878ded814ea02118ea18a0175aae88c#commitcomment-22466850

3) you can download zip fix file here with instructions inside: http://uploadfiles.eu/a7ifyjqo7h2r/Fix_Error_goweil.zip.html

4) download whole zip file from here (GitHub) and make new zip from src directory, in this case you need Goweil_LT_Master.shape from original download file.
you can select option based on your skill 
Apologize for inconvenience.

**Comment by Bede16** [comment]
Awesome.
Its so simple if you know here the problem is.

**Comment by fcelsa** [comment]
fix 1.1.0
