### ISSUE TITLE
destroying of other combis

### ISSUE THREAD

**Issue by The-Alien-Paul** [TeamFSIModding/FS17_Goweil_LT_Master#49]
Hy there :)

The Göweil kills the wraper combi out of the Kuhn DLC, messes up die i3d file of the bales.

[[![https://gyazo.com/4774087c02fbc7331cc4eb661f9c2b29](https://gyazo.com/4774087c02fbc7331cc4eb661f9c2b29/raw)](https://gyazo.com/4774087c02fbc7331cc4eb661f9c2b29)](url)

without Göweil in Modsfolder  [[![https://gyazo.com/99d6719d7acb86b23e140b07b87a488b](https://gyazo.com/99d6719d7acb86b23e140b07b87a488b/raw)](https://gyazo.com/99d6719d7acb86b23e140b07b87a488b)](url)

best regards
Paul

**Comment by fcelsa** [comment]
Thank you for the tip, it's our bales override, will work on update.

**Comment by fcelsa** [comment]
fixed in 1.1.0
