### ISSUE TITLE
Sound error bug 

### ISSUE THREAD

**Issue by criss20ster** [TeamFSIModding/FS17_Goweil_LT_Master#53]
Hello. I have in my log game this error 

Error: Can't load resource 'D:/ModyFS17/mods/FS17_Goweil_LT_Master/sounds/eviscerateSound.wav'.
Error: Can't load sample 'D:/ModyFS17/mods/FS17_Goweil_LT_Master/sounds/eviscerateSound.wav'.

could you fix'it ?

**Comment by fcelsa** [comment]
If you familiar with mod zip manipulation, try this:
unpack the mod, go to sounds folder and rename file evisceratesound.wav to eviscerateSound.wav then zip  the mod again, you are done.

**Comment by criss20ster** [comment]
I have this eviscerateSound.wav but dosent work error resource it's still

**Comment by Dzi4d3k** [comment]
@criss20ster 
You have to name the file exactly like eviscerateSound.wav with capital letter in the middle. Game nad Giants Editor is case sensitive like Linux.

PL version:
Musisz nadać identyczną nazwę, z dużą literą w środku. Gra i edytor Giants rozróżniają duże i małe litery tak jak Linux.

**Comment by criss20ster** [comment]
@Dzi4d3k 
I have done so and it is still a bug (the rest of it I downloaded versions) and she already had these big ones

PL  version:
to tak mam zrobione i nadal jest błąd (z reszta taka pobrałem wersje ) i ona juz miała wpsiane wlasnie te duż elitery

**Comment by Dzi4d3k** [comment]
@criss20ster 
Have you checked official version?
http://www.farming-simulator.com/mod.php?lang=pl&country=pl&mod_id=79815&title=fs2017

I don't get any errors with it.

**Comment by criss20ster** [comment]
I downloaded this version exactly as you write

**Comment by fcelsa** [comment]
what platform: PC or Mac ?

**Comment by criss20ster** [comment]
@fcelsa  PC

**Comment by fcelsa** [comment]
This problem can be tied to personalized location of mod folder I suppose...

**Comment by fcelsa** [comment]
This bug was solved in 62e559011d1f6cde9705410a553644270bc90afa
