### ISSUE TITLE
Problem with FBP3135 balling when LT Master is active on mod list.

### ISSUE THREAD

**Issue by RKI91** [TeamFSIModding/FS17_Goweil_LT_Master#54]
Like in topic tittle.

When i have LT Master active on my mod list, balling with KUHN FBP3135 is not possible. When i make some bale, game starts lagging and gets massive FPS Drops. Not to mention about bale witch is not vissible. This only happens when the KHUN DLC is active on standard maps and also on modded maps.

I apply the language fix but not effect at all. I attach the video with the problem and my game log below.

Video: https://www.youtube.com/watch?v=wNo21lD3ybc&feature=youtu.be
Log: https://gist.github.com/RKI91/a86699c5bf7a65942a4b51e38cd6bf63

**Comment by fcelsa** [comment]
Thank you for detailed report, it's a know bug with bale override and update will be available after mod contest; we are working hard for a best mod experience in game.

**Comment by Appaloosa70** [comment]
Delete all the other mods. Never try wirh an other mod together.  I have no problems. I use together with kuhn dlc and krone ultima 155. also my map have new fruits with new balls. No problems on standard map or modmap.

**Comment by RKI91** [comment]
I tested it without any mods on standard map with only official dlc active and have this problem. LT Master doesn't work well with KUHN DLC in my case.

**Comment by ThaFarmer** [comment]
I have this problem too...
If I have the mod activated(not even purchased) and try to bale-wrap witht the FBP3135, my game freeses as soon as the Baler-wrapper transfers a bale from the chamber to the wrapper. I then have no choice but killing the game with Alt-F4...
Here are my FS forum posts(you should check there sometimes BTW...): 
[Farming Simulator Bug Report](https://forum.giants-software.com/viewtopic.php?f=936&t=113649)

**Comment by ThaFarmer** [comment]
My FS17 game log
[log1.txt](https://github.com/TeamFSIModding/FS17_Goweil_LT_Master/files/1081390/log1.txt)

**Comment by fcelsa** [comment]
fixed in 1.1.0
