### ISSUE TITLE
Still wrapping when turned off.

### ISSUE THREAD

**Issue by DoyleChris98** [TeamFSIModding/FS17_Goweil_LT_Master#55]
Grass Bail is still getting wrapped while the wrapper is turned off.
![bail](https://user-images.githubusercontent.com/29460096/27187671-ccd03b88-51b9-11e7-9708-c3be0be867d9.jpg)

**Comment by TyKonKet** [comment]
You can't avoid wrapping of grass, manure, chaff and woodchips bales.

**Comment by DoyleChris98** [comment]
Yes you can, You have the option to turn off the wrapping and on but that option dosen't work.  And that option does nothing to the operation whether its on or off.

**Comment by Dzi4d3k** [comment]
@DoyleChris98 
I believe @TyKonKet  was meant that this is by design that grass, manure, chaff and woodchips have to be wrapped as net can't be used, that's why with these materials wrapper do not react on settings.

**Comment by DoyleChris98** [comment]
The KRONE ULTIMA CF 155 XC has the ability to turn off the wrapper when bailing grass.
If there is a option to bail grass in bulk, instead of wrapping it.
I wouldn't need to dump grass on the ground to bail it.

**Comment by fcelsa** [comment]
Yes I confirm that grass, manure, chaff and woodchips wrapping it's mandatory, by our choice, it's not a bug, it's a feature that like as is for us.
