### ISSUE TITLE
Is it possible to remap the 'R' for the function 'open an 

### ISSUE THREAD

**Issue by ometinsu** [TeamFSIModding/FS17_Goweil_LT_Master#56]
When i am handeling bale and stack them on trailers, and want to applie the tie-downs i also activate the option to open and fade the bale.
I have tried to remap it myself, but their are no inputbindings in the xml files. Seeing the info of the bales themselves i quite like, that is one of the reasons this is a great mod.
My question  is how can i remap this function or disable it so it no longer interferes with my tie-downs?

**Comment by fcelsa** [comment]
I'm working on new things to solve this behaviour.

**Comment by The-Alien-Paul** [comment]
Please use this, works fine ;)


https://www.modding-welt.com/downloads/entry/2091-g%C3%B6weil-lt-master-steuerungsfix-ballen-aufschneiden/?s=8362b1472205b4454c48ac03806a4e77ddb5b511

**Comment by ometinsu** [comment]
Thanks The-Alien-Paul, this works like a charm and makes bale handeling a lot easier.

**Comment by fcelsa** [comment]
No more workaround script needs, now changed from R key (activate object) to N (toggle cover).
