### ISSUE TITLE
bale filled with uneven amounts

### ISSUE THREAD

**Issue by ShawnTheShadow** [TeamFSIModding/FS17_Goweil_LT_Master#57]
I been noticing when using this, say i filled it to 24k full of a filltype, run one bale, and it's taken the set amount + some extra, like the 5k bale, and it had 18984 rather than 19000 left. And the finished bale seems to be hovering around 4980-5100 full rather than 5000.

**Comment by Dzi4d3k** [comment]
Well, I will call this - more realistic, don't you think?
