### ISSUE TITLE
Silage bales compatibility with Seasons mod

### ISSUE THREAD

**Issue by Dzi4d3k** [TeamFSIModding/FS17_Goweil_LT_Master#59]
Hi,
I just want to ask if you guys plan to make a fix like Realismums Modding did for Krone Ultima, which will fix silage bales being immediately fermented?

**Comment by TyKonKet** [comment]
Yes, it's on the schedule!

**Comment by fcelsa** [comment]
Seasons compatibility is here d5f37db51167efac46d4c393181c6b8eaf193309
