### ISSUE TITLE
No trigger to open side doors?

### ISSUE THREAD

**Issue by thuril** [TeamFSIModding/FS17_Goweil_LT_Master#66]
Hello all,

I realize that this might be a stupid question but I can't find the trigger to open the side doors of the machine, hence I'm unable to use it.
I have circled the machine several times with it both folded and unfolded but never receive the control tip to press N to open the side door(s). The only control tip I receive is to press x to raise/lower the ladder.
There are no errors in my log related to this mod.
Does this mod require any other mods to work properly (like UPK or others). If so maybe I missing it, or I have an outdated version of it.
Or do I have to set up the keys manually for this machine?

Kind regards,
Thuril

**Comment by fcelsa** [comment]
Hello Thuril,
I'm sure no mistery here, you need to set "Automatic engine start" to off in game setting, because the tractors needs to be always on so that Goweil unfold and work as expected.

**Comment by gamerpaddy** [comment]
automatic start = off doesnt fix it, happens randomly. restart usualy fixes it.
sometimes the trigger just disappears.

**Comment by fcelsa** [comment]
see #58 for possible solution
