### ISSUE TITLE
insufficient power available for the attached equipment

### ISSUE THREAD

**Issue by justas1793** [TeamFSIModding/FS17_Goweil_LT_Master#69]
When i click B to turn on it says "insufficient power available for the attached equipment". 
![adadsd](https://user-images.githubusercontent.com/33005871/31864441-251c04c2-b766-11e7-98ac-9fc32fb163ea.png)

**Comment by Dzi4d3k** [comment]
Don't you think this is too small tractor for such a big baller?

**Comment by TyKonKet** [comment]
Yes, this is the reason of the error.

**Comment by Dzi4d3k** [comment]
> Yes, this is the reason of the error.

We would say seriously:
"It's not a bug, it's a feature" :)

**Comment by fcelsa** [comment]
the game message it's very clear, it closes.
