### ISSUE TITLE
Why disable opening bales with seasons?

### ISSUE THREAD

**Issue by bronney** [TeamFSIModding/FS17_Goweil_LT_Master#73]
Hello Matteo,

I am wondering what was the reason to disable opening bales in seasons?  I edited the lua to re-enabled it but I want to know if there's a specific game breaking reason why it was disabled as published.  Thanks.

**Comment by turbostar190** [comment]
Check #68 
Try to download github version after this commit (https://github.com/TeamFSIModding/FS17_Goweil_LT_Master/commit/0183a898386e7fbbc7ba92f48f8b0374435bfee5)

**Comment by bronney** [comment]
Thanks bro.  Looking forward to the update :)  I also deleted the g_seasons if end in the baleInfos.lua
