### ISSUE TITLE
Can start the master

### ISSUE THREAD

**Issue by Bhomipoon** [TeamFSIModding/FS17_Goweil_LT_Master#74]
Hi i am new to the master and dont know and cant see what buttens to use.

**Comment by Dzi4d3k** [comment]
I suggest you to use Youtube for such non-technical and non-issue queries.
There is lot of tutorials. For example
https://www.youtube.com/watch?v=I3_PJEtaYVo

**Comment by Bhomipoon** [comment]
Thz the problem was simpel i have to have the engine runing. I changed that in the game setup and have no more problems. Best regards Thomas
